### ISSUE TITLE
Input and parameter tensors are not the same dtype, found input tensor with Double and parameter tensor with Float

### ISSUE THREAD

**Issue by lijiaoyang** [Rhuax/text-summarization#1]

**Comment by lijiaoyang** [comment]
`output,hidden=self.gru(output,hidden)
`
in encoder.py", line 21,

**Comment by Rhuax** [comment]
The error is really clear. Parameters are defined as `floats `and you're passing doubles. You can simply cast the input to self.gru or (maybe better) define the gru layer with `Double `parameters

**Comment by lijiaoyang** [comment]
thx to your reply!!
But I did not modify your code
Is this bug due to the version of pytorch?

**Comment by lijiaoyang** [comment]
`output=embedded.float()`
I change the encode.py line 17 to this, bug is fixed.
